SET FOREIGN_KEY_CHECKS=0;

DROP DATABASE IF EXISTS `bdsegabank`;

CREATE DATABASE `bdsegabank`
    CHARACTER SET 'latin1'
    COLLATE 'latin1_general_ci';

USE `bdsegabank`;

CREATE TABLE `agence` (
  `ID_AGENCE` INT(4) NOT NULL AUTO_INCREMENT,
  `CODE` INT NOT NULL,
  `ADRESSE` char(20) NOT NULL,
  PRIMARY KEY  (`ID_AGENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `compte` (
  `ID_COMPTE` INT(4) NOT NULL AUTO_INCREMENT,
  `SOLDE` INT(7),
  `ID_AGENCE` INT(4) NOT NULL,
  `DECOUVERT` INT(7),
  `TAUX_INTERET` INT(4),
  PRIMARY KEY  (`ID_COMPTE`),
  KEY `APPARTENIR_FK` (`ID_COMPTE`),
  CONSTRAINT `FK_APPARTENIR` FOREIGN KEY (`ID_AGENCE`) REFERENCES `AGENCE` (`ID_AGENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
